[project]
name = "CondaRTS"
version = "0.0.1"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pygame-ce>=2.5.5",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.12.12",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "ANN",  # flake8-annotations
    "I",  # isort
    "TC",  # flake8-type-checking
]
ignore =[
    "ANN001",  # Missing type annotation for function argument
]

[tool.ruff.lint.per-file-ignores]
# Be lenient with original code:
"CondaRTS.py" = [
    "ANN201",  # Missing return type annotation for public function
    "ANN204",  # ... special method
    "COM812",  # Trailing comma missing - conflicts with ruff format
]
